### ISSUE TITLE
Error while running 

### ISSUE THREAD

**Issue by iloveboobs1** [TheCybersTeam/Sqli#2]
Start Count Columns...
Columns Total: 1Traceback (most recent call last):
  File "sqli.py", line 220, in <module>
    s.setColumns()
  File "sqli.py", line 68, in setColumns
    res = self.getContent(url)
  File "sqli.py", line 55, in getContent
    res = cybers.urlopen(url)
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 469, in open_file
    return self.open_local_file(url)
  File "/usr/lib/python2.7/urllib.py", line 483, in open_local_file
    raise IOError(e.errno, e.strerror, e.filename)
IOError: [Errno 2] No such file or directory: '0x2d31+/*!50000union*/+/*!50000select*/1620597971540027'

**Comment by ItsLeon15** [comment]
Same here
